// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjNCecUjqs86-JQCXNdp-kFFXFMxQB3s',
    appId: '1:726235444490:web:271e6b19508fafc5bc36f3',
    messagingSenderId: '726235444490',
    projectId: 'kendra-e0af8',
    authDomain: 'kendra-e0af8.firebaseapp.com',
    storageBucket: 'kendra-e0af8.appspot.com',
    measurementId: 'G-B9PN22CH45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5pN7L5bjy5JYoa-uZR55XvMtliySpJGo',
    appId: '1:726235444490:android:876635f41a9d0c1ebc36f3',
    messagingSenderId: '726235444490',
    projectId: 'kendra-e0af8',
    storageBucket: 'kendra-e0af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjK8vFea6bIFIeSSX1UYyRx66yT2tyT_M',
    appId: '1:726235444490:ios:127e4c5aaf321656bc36f3',
    messagingSenderId: '726235444490',
    projectId: 'kendra-e0af8',
    storageBucket: 'kendra-e0af8.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjK8vFea6bIFIeSSX1UYyRx66yT2tyT_M',
    appId: '1:726235444490:ios:127e4c5aaf321656bc36f3',
    messagingSenderId: '726235444490',
    projectId: 'kendra-e0af8',
    storageBucket: 'kendra-e0af8.appspot.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIjNCecUjqs86-JQCXNdp-kFFXFMxQB3s',
    appId: '1:726235444490:web:794ffa3b0d4545bbbc36f3',
    messagingSenderId: '726235444490',
    projectId: 'kendra-e0af8',
    authDomain: 'kendra-e0af8.firebaseapp.com',
    storageBucket: 'kendra-e0af8.appspot.com',
    measurementId: 'G-SX502TRV9X',
  );
}
